language: javascript
node_js:
  - 12
script: npm run build
deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    file: './morpher.zip'
    edge: true # opt in to dpl v2
    on:
     tags: true
  - provider: npm
    email: 'master.weber@outlook.com'
    api_token: $NPM_API_TOKEN
    on:
      tags: true
      all_branches: true
    skip_cleanup: true  
